version: '3.8'
services:
  nest:
    container_name: donat_baza_nest
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
  mysql:
    # needed only for dev purposes, to make it work for mac os  
    platform: linux/amd64
    container_name: donat_baza_db 
    restart: always
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db:/var/lib/mysql
    ports:
    - "3307:3306"
volumes:
  db: